version: "3.9"

services:
  app:
    image: begemotic
    container_name: begemotic-web
    build:
      context: ./src/
      dockerfile: ./Docker.dockerfile
    command: sh -c "python main.py"
    working_dir: /apps/
    env_file:
      - .env
    volumes:
      - ./src/:/apps/
    ports:
      - "8000:8000"
    restart: always